//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMasterSovellus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SprintTemplateConnection
    {
        public int TemplateConnectionId { get; set; }
        public int SprintId { get; set; }
        public Nullable<int> SprintTemplateId { get; set; }
    
        public virtual Sprints Sprints { get; set; }
        public virtual SprintTemplate SprintTemplate { get; set; }
    }
}
